# Generated by Django 2.2.4 on 2019-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('about', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='facultet/images/facimages')),
                ('grad_color1', models.CharField(default='#326b02', max_length=10)),
                ('grad_color2', models.CharField(default='#CEF9AB', max_length=10)),
            ],
        ),
    ]
