# Generated by Django 2.2.4 on 2019-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitedu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='facultet/images/trainingimages')),
            ],
        ),
        migrations.AddField(
            model_name='facultet',
            name='trainings',
            field=models.ManyToManyField(related_name='facultet', to='gitedu.training'),
        ),
    ]
