# Generated by Django 2.2.4 on 2019-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitedu', '0002_auto_20191128_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(default='Շուտով', max_length=50),
        ),
    ]
