# Generated by Django 2.2.4 on 2019-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitedu', '0003_auto_20191128_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultet',
            name='sow_in_index',
            field=models.BooleanField(default=False),
        ),
    ]
