# Generated by Django 2.2 on 2020-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitedu', '0005_auto_20191229_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fac', models.CharField(max_length=50)),
                ('tra', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='order_', unique=True),
        ),
    ]
