# Generated by Django 2.2 on 2020-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitedu', '0006_auto_20200104_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordertoserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('serv', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
